{% set name = "junit-xml" %}
{% set version = "1.9" %}
{% set python_tag = 'py2.py3' %}
{% set use_wheel = True %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  {% if use_wheel %}
  - url: https://pypi.org/packages/{{ python_tag }}/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}-{{ python_tag }}-none-any.whl
    sha256: "ec5ca1a55aefdd76d28fcc0b135251d156c7106fa979686a4b48d62b761b4732"
  {% else %}
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: ""
  {% endif %}


build:
  noarch: python
  number: 1
  {% if use_wheel %}
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir -vvv *.whl"
  {% else %}
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed --no-cache-dir -vvv ."
  {% endif %}

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - six

test:
  requires:
    - python {{ python_min }}
  imports:
    - junit_xml

about:
  home: https://github.com/kyrus/python-junit-xml
  license: MIT
  license_file:
    {% if use_wheel %}
    - "{{ name | replace('-', '_') }}-{{ version }}.dist-info/LICENSE.txt"
    {% else %}
    - LICENSE.txt
    {% endif %}
  summary: 'Creates JUnit XML test result documents that can be read by tools such as Jenkins'
  license_family: MIT

extra:
  recipe-maintainers:
    - chapmanb
    - dfornika
    - mariusvniekerk
